name: TypeScript CI Workflow Template

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

permissions:
  contents: read

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  DOCKER_TOKEN: ${{ secrets.DOCKER_HUB }}
 # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  GH_ENV: testing
  CI: true

jobs:
  environment: ${{ github.env.GH_ENV }}
  basic-check:
    name: Basic Check
    uses: ./.github/reusable-workflows/basic-check.yml@main
    with:
      operating-systems: "['ubuntu-latest', 'windows-latest']"

  check-dist:
    name: Check transpiled JavaScript
    uses: ./.github/reusable-workflows/check-dist.yml@main
    with:
      dist-path: "dist"

  integration-test:
    name: Integration Test
    uses: ./.github/reusable-workflows/integration-test.yml@main

