name: Basic TypeScript validation

on:
  workflow_call:
    inputs:
      operating-systems:
        description: "Optional input to set a list of operating systems which the workflow uses. Defaults to ['ubuntu-latest', 'windows-latest', 'macos-latest'] if not set"
        required: false
        type: string
        default: "['ubuntu-latest', 'windows-latest', 'macos-latest']"
      node-version-file:
        description: "Optional input to set the version of Node.js used to build the project. The input syntax corresponds to the setup-node's format as of v4.2.0"
        required: false
        type: string
        default: ".nvmrc"
      pnpm-version:
        description: "Optional input to set the version of pnpm used to build the project. The input syntax corresponds to the pnpm/action-setup's format as of v4.1.0"
      node-caching:
        description: "Optional input to set up caching for the setup-node action. The input syntax corresponds to the setup-node's format as of v4.2.0. Set to an empty string if caching isn't needed"
        required: false
        type: string
        default: "pnpm"

jobs:
  build:
    runs-on: ${{matrix.operating-systems}}
    strategy:
      fail-fast: false
      matrix:
        operating-systems: ${{fromJson(inputs.operating-systems)}}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: pnpm setup
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: Node setup
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install deps, build, and test
        # for now, keeping all pnpm scripts seperate for logging
        run: |-
          pnpm install
          pnpm run lint
          pnpm run format
          pnpm run tsc --if-present
          pnpm run test-ci:unit
          pnpm run build --if-present

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          pattern: dist/*/**

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: dist/test/code-coverage.html